- name: Deploy simple application pod (nginx) - PaaS validation
  hosts: k8s_master
  become: yes
  become_user: ubuntu

  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

  vars:
    app_namespace: app
    pod_name: nginx-app
    service_name: nginx-svc
    nodeport: 30080

  tasks:

    # ------------------------------------------------------------
    # 1. Create namespace
    # ------------------------------------------------------------
    - name: Create app namespace
      shell: kubectl create namespace {{ app_namespace }} --dry-run=client -o yaml | kubectl apply -f -

    # ------------------------------------------------------------
    # 2. Create nginx pod manifest
    # ------------------------------------------------------------
    - name: Create nginx pod manifest
      copy:
        dest: /home/ubuntu/{{ pod_name }}.yaml
        content: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: {{ pod_name }}
            namespace: {{ app_namespace }}
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:latest
              ports:
              - containerPort: 80

    # ------------------------------------------------------------
    # 3. Create NodePort service manifest
    # ------------------------------------------------------------
    - name: Create nginx service manifest
      copy:
        dest: /home/ubuntu/{{ service_name }}.yaml
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: {{ service_name }}
            namespace: {{ app_namespace }}
          spec:
            type: NodePort
            selector:
              app: nginx
            ports:
              - port: 80
                targetPort: 80
                nodePort: {{ nodeport }}

    # ------------------------------------------------------------
    # 4. Apply manifests
    # ------------------------------------------------------------
    - name: Apply nginx pod
      shell: kubectl apply -f /home/ubuntu/{{ pod_name }}.yaml

    - name: Apply nginx service
      shell: kubectl apply -f /home/ubuntu/{{ service_name }}.yaml

    # ------------------------------------------------------------
    # 5. Wait until pod is running
    # ------------------------------------------------------------
    - name: Wait for nginx pod to be Running
      shell: kubectl get pod {{ pod_name }} -n {{ app_namespace }} -o jsonpath='{.status.phase}'
      register: pod_status
      retries: 20
      delay: 5
      until: pod_status.stdout == "Running"

    # ------------------------------------------------------------
    # 6. Show final state
    # ------------------------------------------------------------
    - name: Show nginx pod
      shell: kubectl get pods -n {{ app_namespace }} -o wide
      register: pods_out

    - name: Show nginx service
      shell: kubectl get svc -n {{ app_namespace }}
      register: svc_out

    - name: Display result
      debug:
        msg:
          - "Pods:"
          - "{{ pods_out.stdout_lines }}"
          - "Service:"
          - "{{ svc_out.stdout_lines }}"//and this is the inventory [k8s_master]


